// <auto-generated />

namespace PhotoKiosk.Migrations
{
    using System.Resources;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201804290036000_InitialClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
