// <auto-generated />

namespace PhotoKiosk.Migrations
{
    using System.Resources;
    using System.Data.Entity.Migrations;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PersonPhotoRelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonPhotoRelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201804290048478_PersonPhotoRelationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
